### ISSUE TITLE
Fails to build on DragonFly

### ISSUE THREAD

**Issue by mneumann** [mirage/ocaml-gmp#32]
```
~/Dev/ocaml-gmp % dune build
File "src/dune", lines 14-23, characters 0-357:
14 | (rule
15 |  (targets gmp.h libgmp.a dllgmp.so)
16 |  (deps gmp-6.3.0.tar.xz build.sh gcc.15.patch)
17 |  (action
18 |   (with-stdout-to
19 |    build.log
20 |    (run sh ./build.sh "%{ocaml-config:c_compiler}" "%{ocaml-config:host}"
21 |      "%{ocaml-config:target}" "%{ocaml-config:ocamlc_cflags}"
22 |      %{ocaml-config:supports_shared_libraries}
23 |      "%{ocaml-config:native_c_libraries}"))))
configure: error: could not find a working compiler, see config.log for details
```

[config.log](https://github.com/user-attachments/files/30051166/config.log)

I wonder if the problem is related to `-lpthread` vs `-pthread`

**Comment by hannesm** [comment]
Thanks for your report. The question I have is what does `gcc -dumpversion` return?

The program (named conftest.c) that configure is unhappy about:

```C
/* The following provokes a segfault in the compiler on powerpc-apple-darwin.
   Extracted from tests/mpn/t-iord_u.c.  Causes Apple's gcc 3.3 build 1640 and
   1666 to segfault with e.g., -O2 -mpowerpc64.  */

#if defined (__GNUC__) && ! defined (__cplusplus)
typedef unsigned long long t1;typedef t1*t2;
void g(int, const t1*, t1, t1*, const t1*, int){}
void h(){}
static __inline__ t1 e(t2 rp,t2 up,int n,t1 v0)
{t1 c,x,r;int i;if(v0){c=1;for(i=1;i<n;i++){x=up[i];r=x+1;rp[i]=r;}}return c;}
void f(){static const struct{t1 n;t1 src[9];t1 want[9];}d[]={{1,{0},{1}},};t1 got[9];int i;
for(i=0;i<1;i++){if(e(got,got,9,d[i].n)==0)h();g(i,d[i].src,d[i].n,got,d[i].want,9);if(d[i].n)h();}}
#else
int dummy;
#endif
```

Compiled using `gcc -O2 -pedantic -fomit-frame-pointer -m64 -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread conftest.c -lm -lpthread`

The error from gcc:
```
conftest.c: In function 'g':
conftest.c:7:8: error: parameter name omitted
 void g(int, const t1*, t1, t1*, const t1*, int){}
        ^~~
conftest.c:7:13: error: parameter name omitted
 void g(int, const t1*, t1, t1*, const t1*, int){}
             ^~~~~~~~~
conftest.c:7:24: error: parameter name omitted
 void g(int, const t1*, t1, t1*, const t1*, int){}
                        ^~
conftest.c:7:28: error: parameter name omitted
 void g(int, const t1*, t1, t1*, const t1*, int){}
                            ^~~
conftest.c:7:33: error: parameter name omitted
 void g(int, const t1*, t1, t1*, const t1*, int){}
                                 ^~~~~~~~~
conftest.c:7:44: error: parameter name omitted
 void g(int, const t1*, t1, t1*, const t1*, int){}
                                            ^~~
configure:6588: $? = 1
```

When I remember, your gcc was in version 8, and for solo5 etc. a binary gcc9 is used? For building gmp, the C compiler that has been used for compiling the OCaml compiler & runtime is used (in dune, the `%{ocaml-config:c_compiler}` -- from this invocation, a potential solution would be to compile the OCaml compiler with gcc9 (i.e. `export CC=gcc9` and then do the compilation). You can check with `ocamlc -config | grep c_compiler` what has been used for building the compiler & runtime.

**Comment by mneumann** [comment]
@hannesm correct, the default system compiler `gcc` on DragonFly is gcc 8.3. OCaml on my system was built with it. And ocaml-gmp fails with it.

I hardcoded `ocaml-config:c_compiler` in `src/dune` to `gcc9` and it fails as well:

```
configure:6585: gcc9 -O2 -pedantic -fomit-frame-pointer -m64 -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread conftest.c -lm -lpthread >&5
conftest.c: In function 'g':
conftest.c:7:8: error: parameter name omitted
    7 | void g(int, const t1*, t1, t1*, const t1*, int){}
      |        ^~~
conftest.c:7:13: error: parameter name omitted 
    7 | void g(int, const t1*, t1, t1*, const t1*, int){}
      |             ^~~~~~~~~
conftest.c:7:24: error: parameter name omitted
    7 | void g(int, const t1*, t1, t1*, const t1*, int){}
      |                        ^~
conftest.c:7:28: error: parameter name omitted
    7 | void g(int, const t1*, t1, t1*, const t1*, int){}
      |                            ^~~
conftest.c:7:33: error: parameter name omitted
```

with `gcc11` and onwards (gcc13, gcc14), it works! 

I think we should at least add a check in build.sh (?) for the gcc version to be >= 11. Ideally we'd solve the problem without having to recompile OCaml with a different gcc.

**Comment by hannesm** [comment]
Hmm, strange.. I looked in the DragonFlyBSD ports tree, and math/gmp doesn't have anything special in respect to CC. So I wonder why that one seems to work with the base system gcc (gcc8.3). Any ideas?

**Comment by mneumann** [comment]
@hannesm The "ports" compiler is different from the DragonFly base system compiler:

```
$ /usr/bin/gcc -dumpversion
8.3

$ /usr/local/bin/gcc -dumpversion
11.5.0
```

By default, the ports will be build with gcc11 unless otherwise specified.

**Comment by dinosaure** [comment]
Please note our patch: https://github.com/mirage/ocaml-gmp/blob/main/src/gcc.15.patch which is added **unconditionally**. I think we should apply it only for GCC 15.

**Comment by mneumann** [comment]
@dinosaure ahhh, I think that causes the issues :)

**Comment by hannesm** [comment]
@dinosaure oh right, indeed. Would you try the PR https://github.com/mirage/ocaml-gmp/pull/33

**Comment by mneumann** [comment]
@dinosaure @hannesm PR #33 works if you add "CC=$1" :)

**Comment by hannesm** [comment]
fixed in #33
